name: My First Workflow

on:
    push: 
        branches: 
            - main
            - master

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Run Spring boot app
              run: |
                chmod +x mvnw
                nohup ./mvnw spring-boot:run &
            - name: Test
              run: |
                sleep 10
                curl http://localhost:8080/api/hello