name: My First Workflow

on:
    push: 
        branches: 
            - main
            - master

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Run Spring boot app
              run: |
                mvn -X package
            - name: Test
              run: |
                cd target
                ls -lrtha
                java -jar *.jar
                sleep 10
                curl http://localhost:8080/api/hello