name: My First Workflow

on:
    push: 
        branches: 
            - main
            - master

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'zulu' # See 'Supported distributions' for available options
                java-version: '21'
            - name: Run spring boot
              run: |
                mvn package
                cd target
                ls -lrtha
                # java -jar *.jar
                # sleep 10
                # curl http://localhost:8080/api/hello